### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by lsbromer** [obxd/avatourguide#1]
Hello good afternoon. I'm new to albion and I was looking for a tool for avalon, could you briefly explain how this one works? Grateful.

**Comment by obxd** [comment]
Hello, 

this is how it works: you enter the name of the map (or part of it) and get info about what inside of it that's it 😁.
the ava roads in albion are always same, just the connections change.

I just added a release for windows or build instructions if you want to try.
if i did everything correctly all you need to do is download the avatourguide.exe  and run it

This tool uses data which extracted from the extracted data here [ao-bin-dumps](https://github.com/broderickhyman/ao-bin-dumps)

**Comment by lsbromer** [comment]
Thank you so much for making this available. I'm trying to use.
